name: Cookie Method

on:
  schedule:
    - cron: '30 2 * * *' 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Private Resume
        run: |
          curl -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
          -H "Accept: application/vnd.github.v3.raw" \
          -o "resume.pdf" \
          -L "https://raw.githubusercontent.com/SukhbirSinghKhalsa/NOTES/updater/sukhbir-devops.pdf"

      - name: Setup Playwright
        run: |
          npm install playwright
          npx playwright install chromium --with-deps

      - name: Run Script
        env:
          NAUKRI_COOKIES: ${{ secrets.NAUKRI_COOKIES }}
          RESUME_PATH: "./resume.pdf"
        run: node .github/scripts/updater.js
